description: Prepares the repo for a typical CI job

name: Prepare

inputs:
  node-version:
    description: Node.js version to use
    default: "lts/*"
    required: false

runs:
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
