description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v4
      with:
       node-version: '20'
    - run: npm ci
      shell: bash
  using: composite
