jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: npm run tsc

name: Type Check

on:
  pull_request: ~
  push:
    branches:
      - main
